apiVersion: apps/v1
kind: Deployment
metadata:
  name: scfleets-pilot-worker-deployment
  labels:
    app: scfleets-pilot-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scfleets-pilot-worker
  template:
    metadata:
      labels:
        app: scfleets-pilot-worker
    spec:
      containers:
        - name: scfleets-pilot-worker
          image: kwalter26/scfleets-pilot-worker:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: scfleets-pilot-worker-config
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: scfleets-secrets
                  key: cognito-client-id
            - name: CLIENT_PASS
              valueFrom:
                secretKeyRef:
                  name: scfleets-secrets
                  key: cognito-client-secret
            - name: RABBIT_URL
              valueFrom:
                secretKeyRef:
                  name: scfleets-secrets
                  key: rabbitmq-addresses
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: scfleets-secrets
                  key: cognito-access-token-uri
            - name: SCOPE
              valueFrom:
                secretKeyRef:
                  name: scfleets-secrets
                  key: cognito-client-scope
