spring:
  rabbitmq:
    addresses: ${RABBIT_URL}
  cloud:
    stream:
      bindings:
        pilotInfo-in-0:
          destination: pilot-info-events
          group: v1-consumers
basic-auth: ${CLIENT_ID}:${CLIENT_PASS}
auth-url: ${AUTH_URL}
grant: ${GRANT}
scope: ${SCOPE}
com:
  scfleets:
    baseUrl: ${BASE_URL}
    pilotUri:
      updatePilotRsiProfile: ${UPDATE_PILOT_RSI_PROFILE_URI}
    accountUir:
      accountAuthById: ${ACCOUNT_AUTH_BY_ID_URI}
    spectrumClient:
      baseUrl: ${RSI_BASE_URL}
      messageUri: ${MESSAGE_URI}
      lobbyInfoUri: ${LOBBY_INFO_URI}
      autocompleteUri: ${AUTOCOMPLETE_URI}